# PlatformIO pre: extract LineString from Circuit1/2/3.kmz → include/circuit_paths_generated.h
import re
import zipfile
from pathlib import Path

try:
    Import("env")  # noqa: F821  — SCons symbol when run by PlatformIO
    PROJECT_DIR = Path(env["PROJECT_DIR"])
except NameError:
    PROJECT_DIR = Path(__file__).resolve().parent.parent
OUT_H = PROJECT_DIR / "include" / "circuit_paths_generated.h"
COORD_RE = re.compile(
    r"<coordinates>\s*([^<]+?)\s*</coordinates>",
    re.IGNORECASE | re.DOTALL,
)


def _linestring_triples(kml_text: str):
    m = COORD_RE.search(kml_text)
    if not m:
        raise ValueError("No <coordinates> block found in KML")
    raw = m.group(1).replace("\n", " ").replace("\t", " ").strip()
    triples = []
    for tok in raw.split():
        if not tok:
            continue
        parts = [p.strip() for p in tok.split(",")]
        if len(parts) < 2:
            continue
        lon = float(parts[0])
        lat = float(parts[1])
        alt = float(parts[2]) if len(parts) >= 3 and parts[2] != "" else 0.0
        triples.append((lon, lat, alt))
    if len(triples) < 2:
        raise ValueError("LineString needs at least 2 vertices")
    return triples


def _read_kml_from_kmz(kmz_path: Path) -> str:
    with zipfile.ZipFile(kmz_path, "r") as zf:
        names = zf.namelist()
        doc = next((n for n in names if n.lower().endswith(".kml")), None)
        if not doc:
            raise FileNotFoundError(f"No .kml inside {kmz_path}")
        return zf.read(doc).decode("utf-8", errors="replace")


def main():
    lines = [
        "// AUTO-GENERATED by scripts/kmz_to_circuit_paths.py — do not edit.",
        "// Source: Circuit1.kmz, Circuit2.kmz, Circuit3.kmz (first Placemark LineString).",
        "#pragma once",
        "#include <cstddef>",
        "",
    ]
    for idx in (1, 2, 3):
        kmz = PROJECT_DIR / f"Circuit{idx}.kmz"
        if not kmz.is_file():
            raise FileNotFoundError(f"Missing {kmz.name} (expected next to platformio.ini)")
        kml = _read_kml_from_kmz(kmz)
        triples = _linestring_triples(kml)
        n = len(triples)
        var = f"kCircuitKmz{idx}"
        lines.append(f"static constexpr size_t {var}PointCount = {n};")
        lines.append(f"static const double {var}Points[{var}PointCount][3] = {{")
        for lon, lat, alt in triples:
            lines.append(f"    {{{lon:.17g}, {lat:.17g}, {alt:.17g}}},")
        lines.append("};")
        lines.append("")
    OUT_H.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    if OUT_H.is_file() and OUT_H.read_text() == text:
        print("kmz_to_circuit_paths: include/circuit_paths_generated.h unchanged")
    else:
        OUT_H.write_text(text)
        print(f"kmz_to_circuit_paths: wrote {OUT_H.relative_to(PROJECT_DIR)}")


main()
